### ISSUE TITLE
Support Sentry Performance API

### ISSUE THREAD

**Issue by dnlup** [immobiliare/fastify-sentry#115]
In its latest versions Sentry has added tracing performance capabilities, it would be nice to be able to support that, using an option to enable/disable the functionality or maybe using a separate plugin 🤔

**Comment by kurtwiersma-imaware** [comment]
I used info from this Fastify issue comment to create my own Sentry APM Fastify plugin. It would be awesome if something like this were part of this package.

https://github.com/fastify/help/issues/601#issuecomment-1128991983

```typescript
export default fp(async (app: FastifyInstance, options: SentryPluginOptions) => {
  Sentry.init({
    dsn: options.dsn,
    environment: options.environment,
    integrations: [
      // enable HTTP calls tracing
      new Sentry.Integrations.Http({ tracing: true }),
      // Adjusts the pathing of the stack trace, to support pointing from the compiled JS files
      new RewriteFrames({ root: global.__rootdir__ }),
      new ExtraErrorData(),
    ],
    release: options.release,
    tracesSampleRate: 1.0,
    enabled: options.enabled,
  });

  Sentry.configureScope((scope) => {
    scope.addEventProcessor((event) => {
      const traceData = event.contexts?.trace?.data as {
        user?: {
          uid: string;
          upn: string;
          ip: string;
        };

        request?: {
          method: string;
        };
      };

      if (!traceData) {
        return event;
      }

      const { user } = traceData;
      if (user) {
        // eslint-disable-next-line no-param-reassign
        event.user = {
          id: user.uid,
          username: user.upn,
          email: user.upn,
          ip_address: user.ip,
          ...event.user,
        };
      }

      const { request } = traceData;
      if (request) {
        // eslint-disable-next-line no-param-reassign
        event.request = {
          method: request.method,
          ...event.request,
        };
      }

      return event;
    });
  });

  app.decorateRequest('sentryTx', null);

  app.addHook('onRequest', (request: FastifyRequest, _reply: FastifyReply, done) => {
    request.sentryTx = Sentry.startTransaction({
      name: `${request.method} ${request.url}`,
      op: 'http.server',
      description: 'HTTP request',
    });
    request.sentryTx.setData('request', { method: request.method });
    done();
  });

  app.addHook('onResponse', (request: FastifyRequest, reply: FastifyReply, done) => {
    request.sentryTx.setHttpStatus(reply.statusCode);
    request.sentryTx.finish();
    done();
  });
});
```

**Comment by dnlup** [comment]
Thank you @kurtwiersma-imaware , this is really good stuff. I don't have a timeline atm, but this feature is certainly planned to be in this package 😉 , right after #114 has landed. We are trying to get inspiration from the official express integration to implement it.

**Comment by dnlup** [comment]
Hi @kurtwiersma-imaware in #114 we are trying to improve the plugin integration with sentry and, among other things, we are adding support for the performance api.

**Comment by lehno** [comment]
I got to see the performance working nicely now, the only thing missing is httpCode (it always shows no value) and the user is missing. I'm using the extract user data function and still no luck.
Any idea of what it could be?

**Comment by dnlup** [comment]
Thanks @lehno for the heads up. 
The user is extracted from a predefined key in the request that might not be the one you are using to store that data. Can you post an example of the custom function you are using?
About the httpCode, can you post a screen of an event?

**Comment by dnlup** [comment]
Sorry I closed this by mistake

**Comment by lehno** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/5764569/203812605-e1aaa9a1-3681-411d-8d3c-b841ad469938.png">
As you can see, HTTP shows no value

**Comment by lehno** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/5764569/203812943-5d1a218f-35aa-4d80-92f3-f179fb9d602e.png">
And here I extract the user data with the custom function provided

**Comment by dnlup** [comment]
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/5764569/203812605-e1aaa9a1-3681-411d-8d3c-b841ad469938.png">
> 
> As you can see, HTTP shows no value

Thank you @lehno this is very useful 😉

**Comment by dnlup** [comment]
> <img alt="image" width="405" src="https://user-images.githubusercontent.com/5764569/203812943-5d1a218f-35aa-4d80-92f3-f179fb9d602e.png">
> 
> And here I extract the user data with the custom function provided

Ok, the function is correct. I am  sure that the user data should show up in an `event`, are you expecting it in a `transaction` too? If so, I am not sure the other integrations do that either. I will do more research on it.

**Comment by lehno** [comment]
Yes, I am expecting this in a transaction for performance monitoring, so we can sometimes contact the user. Let me know if you need more help

**Comment by dnlup** [comment]
Thank you for clarifying @lehno . Regarding the http code missing, there must be something strange going on [here](https://github.com/immobiliare/fastify-sentry/blob/main/lib/request.js#L118), I'll look into it. For the user data instead, I'll have to do a bit more research to see how it's implemented in express and how it can be ported here.
