### ISSUE TITLE
Fastify v4 support

### ISSUE THREAD

**Issue by nkrass** [immobiliare/fastify-sentry#152]
Hi guys, is there any plan to update deps to support fastify v4 any time soon?
Would be great to test it.
Have a great day!

**Comment by dnlup** [comment]
Hey @nkrass , thanks for opening this. Yes, we are planning to support version 4 now that it's out of rc status. As far as I can see there are no breaking changes between 3 and 4 that impact this plugin, but we are going to be sure after @simonecorsi finishes his tests.  I think we are going to open a PR soon 😉 .

**Comment by simonecorsi** [comment]
Closed in #152 🎉
