### ISSUE TITLE
Sentry 7.17 is breaking installation

### ISSUE THREAD

**Issue by simonecorsi** [immobiliare/fastify-sentry#274]
https://github.com/getsentry/sentry-javascript/issues/6066

Pinning ti 7.16 temporarily to avoid breaking people npm install

**Comment by AbhiPrasad** [comment]
This has been fixed [with the `7.17.1` release](https://github.com/getsentry/sentry-javascript/releases/tag/7.17.1) - sorry for the trouble!

**Comment by simonecorsi** [comment]
Hey, @AbhiPrasad thank you for letting me know! 🙏
