### ISSUE TITLE
parseBaggageString is not a function

### ISSUE THREAD

**Issue by MLforAll** [immobiliare/fastify-sentry#316]
**Issue**

Hello. We started using your package to integrate Sentry into our Fastify applications. It worked really great until we integrated Sentry into another application which calls the first one.

I found that this is related to `baggage`, hence why the issue only appears when Sentry is enabled in the caller app.
I then looked at Sentry's SDK code and found that the `parseBaggageString()` function has been renamed to `parseBaggageHeader()` [in version 7.3.0](https://github.com/getsentry/sentry-javascript/compare/7.2.0...7.3.0).

**Versions**

- `node`: 16.18.1
- `fastify`: 4.6.0
- `@immobiliarelabs/fastify-sentry`: 5.0.0
- `@sentry/*`: 7.18.0

**Comment by dnlup** [comment]
@MLforAll Thank you for the detailed report. So if I understand correctly, this issue comes up only with distributed tracing, right? 🤔  To reproduce, I could make a dummy app using Sentry that calls an http service written in fastify that is using this plugin

**Comment by dnlup** [comment]
I tested locally and I could not reproduce the issue, I think because the `sentry-trace` header is not set:

```js
import fastify from 'fastify'
import sentry from '@immobiliarelabs/fastify-sentry'
import { fetch } from 'undici'

const DSN = 'some private din';
const ENV = 'fastify-sentry'

const OPTS = {
  logger: true
}

const app1 = fastify(OPTS)
app1.register(sentry, {
  dsn: DSN,
  environment: ENV,
  tracesSampleRate: 1
})
app1.get('/call-1', async () => { 
  return { some: true }
})

const app2 = fastify(OPTS)
app2.register(sentry, {
  dsn: DSN,
  environment: ENV,
  tracesSampleRate: 1
})

app2.get('/call-2', async (req, reply) => {
  const response = await fetch('http://localhost:5000/call-1')
  const payload = await response.json();
  return payload;
})

app1.listen({ port: 5000 })
app2.listen({ port: 4000 })
```

@MLforAll  are you manually setting this header? With the options passed sentry should set the header to the response, so it could be something to look into additionally to what you reported.

**Comment by dnlup** [comment]
After looking again into the express integration, I found a way to manually add those headers:

```js
import fastify from 'fastify'
import sentry from '@immobiliarelabs/fastify-sentry'
import { fetch } from 'undici'

const DSN = 'some private dsn';
const ENV = 'fastify-sentry'

const OPTS = {
  logger: true
}

const app1 = fastify(OPTS)
app1.register(sentry, {
  dsn: DSN,
  environment: ENV,
  tracesSampleRate: 1
})
app1.get('/call-1', async () => { 
  return { some: true }
})

const app2 = fastify(OPTS)
app2.register(sentry, {
  dsn: DSN,
  environment: ENV,
  tracesSampleRate: 1
})

app2.get('/call-2', async (req, reply) => {
    const response = await fetch('http://localhost:5000/call-1', { headers: {
      'sentry-trace': '12312012123120121231201212312012-1121201211212012-0',
      baggage: 'sentry-version=1.0,sentry-environment=fastify-sentry',
    }})
  const payload = await response.json();
  return payload;
})

app1.listen({ port: 5000 })
app2.listen({ port: 4000 })
```

And I can see the error now. I think this issue exposes a few other things in that logic that we should update, I'll work on it.

**Comment by MLforAll** [comment]
Hello, and sorry for the delayed response.

The "caller" app is using Express.js and the "callee" app is using Fastify.

Here's how Sentry is initialised in the Express.js app:

```ts
Sentry.init({
	dsn: process.env.SENTRY_DSN,
	environment: process.env.NODE_ENV,
	release: process.env.APP_VERSION,
	integrations: [
		new Sentry.Integrations.Http({ tracing: true }),
		new Tracing.Integrations.Express({ app })
	]
})
```

What sets the `baggage` header is the `Http` integration (`Sentry.Integrations.Http`).
