### ISSUE TITLE
how can i add support for profiling?

### ISSUE THREAD

**Issue by bigansh** [immobiliare/fastify-sentry#350]
hey, i see that i need to import sentry transactions to be imported first then profiling import. how can i add profiling using the library?

**Comment by dnlup** [comment]
hi @bigansh , we haven't looked into profiling support just yet, can you show me an example of the problem you are having? From the documentation it looks like profiling it's an `integration` to pass via options:

https://docs.sentry.io/platforms/node/profiling/

**Comment by dnlup** [comment]
Is this still a problem, can we close it?

**Comment by bigansh** [comment]
hey, yes please. sorry.
