### ISSUE TITLE
Pinned Sentry version

### ISSUE THREAD

**Issue by Xhale1** [immobiliare/fastify-sentry#357]
Is there a reason why Sentry versions are now pinned instead of using a `^` range? This seems to have changed in v5.0.1, just curious if that's actually needed.

**Comment by dnlup** [comment]
Hi @Xhale1 , yes there is a reason. An in-range update of Sentry caused  #316, so I decided to pin a specific version to have more control and to avoid something similar to happen again. I have seen using this strategy inside the Sentry SDK too.

**Comment by Xhale1** [comment]
Sounds good, thanks for the answer :)
