### ISSUE TITLE
Cannot use in bundled application - missing package.json 

### ISSUE THREAD

**Issue by bagr001** [immobiliare/fastify-sentry#393]
Hi, thank you for your work, I love your integration.

I used this plugin in my app that is bundled into single file during build, but i stumbled on an obstacle.
During runtime, there si `require` call  for `package.json` via relative path, which cannot be bundled at current state.

Is there a possibility to change this behavior to support code bundling?

I've tested one sollution. Changing

```
const PACKAGE_NAME = require(path.resolve(__dirname, 'package.json')).name;
```

to

```
const PACKAGE_NAME = require('./package.json').name;
```

would help :-)

Thanks!

https://github.com/immobiliare/fastify-sentry/blob/183806741622798735f294805a196c940afbd066/index.js#L16

**Comment by dnlup** [comment]
Hi @bagr001 , thank you for opening this. Yes it's possible, PRs are welcome if you have the time to work on it 😉 . Otherwise I'll look into it

**Comment by dnlup** [comment]
We could also just hardcode the plugin name in the `exports` 😉

**Comment by simonecorsi** [comment]
> We could also just hardcode the plugin name in the `exports` 😉

Yep, I second this, it's just a string that won't change, we'll one less thing to worry about if/when moving to ESM 👍

**Comment by dnlup** [comment]
This should be fixed now, thanks @bagr001
