### ISSUE TITLE
Improve the allowedStatusCode option override

### ISSUE THREAD

**Issue by simonecorsi** [immobiliare/fastify-sentry#5]
Avoid having a big array with all the status code and see if we can do some filtering based on strings, eg: `5xx`

**Comment by yurtaev** [comment]
I'm using [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) like `allowedStatusCodes.has(reply.statusCode)` to improve performance.
