### ISSUE TITLE
Mark Sentry dependencies with caret mark

### ISSUE THREAD

**Issue by fedorov-xyz** [immobiliare/fastify-sentry#609]
Currently all Sentry deps of fastify-sentry have strict versions:

```json
 "dependencies": {
    "@sentry/node": "7.59.2",
    "@sentry/tracing": "7.59.2",
    "@sentry/utils": "7.59.2",
  },
```

It means that if I need to install `@sentry/node` to my project separatly to use some functions from it, I have to sync versions. If I use versions with caret (`^7.60.0`), yarn installs all sentry deps in 2 places:

- project/node_modules — my project
- project/node_modules/@sentry/node/node_modules/ — that's a problem

That causes type errors:

<img width="1219" alt="image" src="https://github.com/immobiliare/fastify-sentry/assets/25563268/c170a990-081c-48e6-a568-3aa83a8bdc28">

If we look to yarn.lock file, we could find that all Sentry version have duplicates with no caret:

<img width="1099" alt="image" src="https://github.com/immobiliare/fastify-sentry/assets/25563268/8bd9049a-a84d-4d24-9692-02febdc59837">

So, my suggestion is to prefix all versions with caret:

```json
 "dependencies": {
    "@sentry/node": "^7.59.2",
    "@sentry/tracing": "^7.59.2",
    "@sentry/utils": "^7.59.2",
  },
```

Specifying strict resolution in package.json is a workaround

<img width="500" alt="image" src="https://github.com/immobiliare/fastify-sentry/assets/25563268/279fd362-53d1-4f62-900c-4258e6172dee">

**Comment by fedorov-xyz** [comment]
I could make a PR to do it, if that suggestion will be ok for you.

**Comment by dnlup** [comment]
Hi @fedorov-xyz , to give a little context on the reason behind pinning the exact version:

https://github.com/immobiliare/fastify-sentry/issues/316

On a non-breaking update of sentry we encountered breaking changes on some internals (not public, so understandable) functions we were using in this plugin. The team at sentry have done an amazing work to refactor the sdk api internals, so it might be not a great issue anymore. I am not against removing the pinned version and using the caret. Just out of curiosity, isn't viable for you to use the sdk instance exposed on the fastify instance (`fastify.Sentry`)?
