### ISSUE TITLE
Types break when using with typescript

### ISSUE THREAD

**Issue by shoxsz** [immobiliare/fastify-sentry#615]
Hello guys, just wanted to let you know about an issue with typescript types for this module, when using `moduleResolution: Node16` it causes some errors when trying to import the default exported fastify plugin callback, you can check this out here [https://arethetypeswrong.github.io/?p=%40immobiliarelabs%2Ffastify-sentry%406.0.10](url)

**Comment by nnennajohn** [comment]
Hi @simonecorsi ,

I get an error that the dsn property does not exist in the plugin option. You can also see that it is not declared in the published types for 7.0.0.

Was this missed?

Thanks.

<img width="790" alt="Screenshot 2023-08-26 at 6 07 02 PM" src="https://github.com/immobiliare/fastify-sentry/assets/1761197/0d0adaf4-6540-4e50-918f-04cf80fc582e">

**Comment by dnlup** [comment]
> Hi @simonecorsi ,
> 
> I get an error that the dsn property does not exist in the plugin option. You can also see that it is not declared in the published types for 7.0.0.
> 
> Was this missed?
> 
> Thanks.
> 
> <img alt="Screenshot 2023-08-26 at 6 07 02 PM" width="790" src="https://user-images.githubusercontent.com/1761197/263498935-0d0adaf4-6540-4e50-918f-04cf80fc582e.png">

Hi @nnennajohn , thank you for reporting this. I think I missed it in this latest release. I'll fix it

**Comment by dnlup** [comment]
So, I definitely missed to extend the `Sentry.NodeOptions` interface.

Strangely I am getting errors anyway, also using the previous release

<img width="1205" alt="Screenshot 2023-08-28 alle 12 08 08" src="https://github.com/immobiliare/fastify-sentry/assets/15520377/4713b1dc-36c2-4f4a-a9da-78ceef5bfc08">

and this is confusing me 🤔

**Comment by dnlup** [comment]
@nnennajohn Let me know if there are still issues with types, thanks again 😉

**Comment by nnennajohn** [comment]
Great. Thanks so much. Will update and test it out.
