### ISSUE TITLE
Support skipping call to `Sentry.init()`

### ISSUE THREAD

**Issue by spaceemotion** [immobiliare/fastify-sentry#621]
I am using a fastify server inside of AWS Lambda and thus already have a Sentry instance initialized. It would be nice to have an option to simply skip the Sentry initalization step to not confuse the library.

**Comment by dnlup** [comment]
Hi @spaceemotion , thank you for opening this. I am looking at the docs [here](https://docs.sentry.io/platforms/node/guides/aws-lambda/) and [here](https://docs.sentry.io/product/integrations/cloud-monitoring/aws-lambda) and I can see the use case. Would a simple `boolean` flag in the plugin options be enough?

```js
fastify.register(fastifySentryPlugin, {
  skipInit: true
})
```

or do we need something more?

**Comment by spaceemotion** [comment]
No, I think think that flag should do it :)
