### ISSUE TITLE
Fastify Deprecated warning

### ISSUE THREAD

**Issue by tomasstrejcek** [immobiliare/fastify-sentry#628]
(node:15939) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.

probably from line in[ utils.js:88](https://github.com/immobiliare/fastify-sentry/blob/d16a3970b51d36a066c83b51d75a4f233134a287/utils.js#L88)

can I send PR?

**Comment by dnlup** [comment]
Hi @tomasstrejcek , thank you for opening this.

I also see this deprecation when running tests:

<img width="951" alt="Screenshot 2023-09-14 alle 10 03 18" src="https://github.com/immobiliare/fastify-sentry/assets/15520377/60e944cb-4e64-4449-b7e7-93d8150c946e">

So there must some other place too maybe. Of course you can send a PR, thank you 🙏
